# Predicciones de una red neuronal entrenada

In [1]:
import numpy as np

# Caragamos los valores de los parámetros omega y beta
omegas = np.array([[6.46, 19.64], [-1.6, -1.35], [-3.43, -7.52]])
betas = np.array([[-5.47, -3.76, 3.96], [7.61, -8.21, -3.81], [1.9, 7.87, -8.46]])

# Escribimos X como una matriz 12x2
n_inst = 12
Xs = np.array([1.5, 0.2, 1.4, 0.3, 1.6, 0.4, 1.1, 0.1, 4.3, 1.3, 3, 1.1, 4.9, 2,
              6.1, 1.9, 4.4, 1.2, 5.9, 2.1, 5.6, 1.4, 5, 1.9])
Xs = np.reshape(Xs, newshape = (n_inst, 2))

# Escribimos y como un array 1-D
y = np.array([1, 1, 1, 2, 1, 2, 2, 2, 3, 1, 3, 3])

print(f'Valores de Omega ->\n {omegas}')
print(f'Valores de beta ->\n {betas}')
print(f'Valores de entrada ->\n {Xs}')
print(f'Clases de entrada ->\n {y}')

Valores de Omega ->
 [[ 6.46 19.64]
 [-1.6  -1.35]
 [-3.43 -7.52]]
Valores de beta ->
 [[-5.47 -3.76  3.96]
 [ 7.61 -8.21 -3.81]
 [ 1.9   7.87 -8.46]]
Valores de entrada ->
 [[1.5 0.2]
 [1.4 0.3]
 [1.6 0.4]
 [1.1 0.1]
 [4.3 1.3]
 [3.  1.1]
 [4.9 2. ]
 [6.1 1.9]
 [4.4 1.2]
 [5.9 2.1]
 [5.6 1.4]
 [5.  1.9]]
Clases de entrada ->
 [1 1 1 2 1 2 2 2 3 1 3 3]


In [2]:
# Calcuamos las funciones de transferencia
B1 = np.zeros(shape = (n_inst, ))
B2 = np.zeros(shape = (n_inst, ))
Bs = np.zeros(shape = (n_inst, 2))
for i in range(n_inst):  
    B1[i] = 1 / (1 + np.exp(-(omegas[0, 0] + np.sum(omegas[1:, 0] * Xs[i, :]))))
    B2[i] = 1 / (1 + np.exp(-(omegas[0, 1] + np.sum(omegas[1:, 1] * Xs[i, :]))))
    Bs[i, :] = np.array([B1[i], B2[i]])

print(B1)
print(B2)
print(Bs)

[9.66882015e-01 9.60494183e-01 9.26081561e-01 9.87345411e-01
 7.54722113e-03 1.07839696e-01 2.63814633e-04 5.45139179e-05
 9.04909715e-03 3.78061864e-05 6.73734823e-04 3.16775630e-04]
[0.9999999  0.99999981 0.99999948 0.99999997 0.98302679 0.99933695
 0.11763699 0.05300036 0.99076979 0.0160321  0.82520241 0.19813367]
[[9.66882015e-01 9.99999899e-01]
 [9.60494183e-01 9.99999813e-01]
 [9.26081561e-01 9.99999481e-01]
 [9.87345411e-01 9.99999972e-01]
 [7.54722113e-03 9.83026787e-01]
 [1.07839696e-01 9.99336952e-01]
 [2.63814633e-04 1.17636992e-01]
 [5.45139179e-05 5.30003604e-02]
 [9.04909715e-03 9.90769786e-01]
 [3.78061864e-05 1.60321049e-02]
 [6.73734823e-04 8.25202406e-01]
 [3.16775630e-04 1.98133673e-01]]


In [3]:
# Calculamos la salida de la red
C1 = np.zeros(shape = (n_inst, ))
C2 = np.zeros(shape = (n_inst, ))
C3 = np.zeros(shape = (n_inst, ))
Cs = np.zeros(shape = (n_inst, 3))

for i in range(n_inst):
    C1[i] = 1 / (1 + np.exp(-(betas[0, 0] + np.sum(betas[1:, 0] * Bs[i, :]))))
    C2[i] = 1 / (1 + np.exp(-(betas[0, 1] + np.sum(betas[1:, 1] * Bs[i, :]))))
    C3[i] = 1 / (1 + np.exp(-(betas[0, 2] + np.sum(betas[1:, 2] * Bs[i, :]))))
    Cs[i, :] = np.array([C1[i], C2[i], C3[i]])

print(C1)
print(C2)
print(C3)

[0.97785981 0.97678256 0.97004016 0.98099189 0.02806366 0.06005279
 0.00524886 0.00463772 0.02878555 0.00432396 0.01989896 0.00611343]
[0.02128783 0.02240834 0.02950823 0.01805512 0.98043891 0.9615585
 0.05539054 0.03411411 0.98134967 0.02572732 0.93870549 0.09945555]
[2.79055821e-04 2.85928943e-04 3.25974178e-04 2.58130846e-04
 1.23075127e-02 7.35305009e-03 9.50911019e-01 9.71010660e-01
 1.14710728e-02 9.78631229e-01 4.63630920e-02 9.07424195e-01]


In [4]:
# Escogemos la clase predicha en cada caso
y_pred = np.argmax(Cs, axis = 1) + 1
y_pred

array([1, 1, 1, 1, 2, 2, 3, 3, 2, 3, 2, 3], dtype=int64)

In [5]:
# Generamos un DataFrame para mayor facilidad de visualización del resultado
import pandas as pd
df = pd.DataFrame({"X1":Xs[:, 0], "X2":Xs[:, 1], 
                  "B1":B1, "B2":B2, "p(C1)":C1,
                  "p(C2)":C2, "p(C3)":C3, 
                  "Predicha":y_pred, "Real":y})
df

X1   X2        B1        B2     p(C1)     p(C2)     p(C3)  Predicha  Real
0   1.5  0.2  0.966882  1.000000  0.977860  0.021288  0.000279         1     1
1   1.4  0.3  0.960494  1.000000  0.976783  0.022408  0.000286         1     1
2   1.6  0.4  0.926082  0.999999  0.970040  0.029508  0.000326         1     1
3   1.1  0.1  0.987345  1.000000  0.980992  0.018055  0.000258         1     2
4   4.3  1.3  0.007547  0.983027  0.028064  0.980439  0.012308         2     1
5   3.0  1.1  0.107840  0.999337  0.060053  0.961559  0.007353         2     2
6   4.9  2.0  0.000264  0.117637  0.005249  0.055391  0.950911         3     2
7   6.1  1.9  0.000055  0.053000  0.004638  0.034114  0.971011         3     2
8   4.4  1.2  0.009049  0.990770  0.028786  0.981350  0.011471         2     3
9   5.9  2.1  0.000038  0.016032  0.004324  0.025727  0.978631         3     1
10  5.6  1.4  0.000674  0.825202  0.019899  0.938705  0.046363         2     3
11  5.0  1.9  0.000317  0.198134  0.006113  0.099456  0.907424         3     3

In [6]:
# Comenzamos a calcular las metricas de clasificación
import classification_metrics as cm

confusion_matrix = cm.confusion_matrix(y, y_pred)
funcs = [cm.accuracy, cm.recall, cm.fp_rate, cm.specificity, cm.precission, cm.f1_score, cm.kappa]
metrics = [func(confusion_matrix) for func in funcs]
res_df = pd.DataFrame({"CCR":metrics[0], "Recall":metrics[1], "Fp Rate":metrics[2],
                        "Especifidad":metrics[3], "Precision":metrics[4], "F1 Score":metrics[5],
                        "Kappa":metrics[6]}, index = list(range(1,4)))
print(f"\n\nMetricas de clasificación -> \n")
res_df



Metricas de clasificación -> 



CCR    Recall   Fp Rate  Especifidad  Precision  F1 Score  Kappa
1  0.416667  0.600000  0.142857     0.857143       0.75  0.666667  0.125
2  0.416667  0.250000  0.375000     0.625000       0.25  0.250000  0.125
3  0.416667  0.333333  0.333333     0.666667       0.25  0.285714  0.125

En general, vemos como el clasificador alcanza un rendimiento un tanto pobre, especialmente clasificando en las clases 2 y 3 (como puede verse de los valores de precisión por clase).